set CONTAINER_REPOSITORY_NAME=windows/iis
set IMAGE_TAG=v0.0.1
set CONTAINER_IMAGE_URL_WITH_TAG=%CONTAINER_REGISTRY_URL%/%CONTAINER_REPOSITORY_NAME%:%IMAGE_TAG%

docker build -t %CONTAINER_IMAGE_URL_WITH_TAG% .
docker push %CONTAINER_IMAGE_URL_WITH_TAG%
