---
apiVersion: v1
kind: Namespace
metadata:
  name: windows
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-iis
  namespace: windows
spec:
  selector:
    matchLabels:
      app: windows-iis
  replicas: 2
  template:
    metadata:
      labels:
        app: windows-iis
    spec:
      containers:
      - name: windows-iis
        image: 328800402445.dkr.ecr.us-east-1.amazonaws.com/windows/iis:v0.0.1
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: windows-iis
  namespace: windows
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: windows-iis
  type: LoadBalancer
