---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-iis
  namespace: dotnet
spec:
  selector:
    matchLabels:
      app: windows-iis
  replicas: 2
  template:
    metadata:
      labels:
        app: windows-iis
    spec:
      containers:
      - name: windows-iis
        image: 328800402445.dkr.ecr.us-east-1.amazonaws.com/windows/iis:v0.0.1
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: windows
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - windows-iis
      #       topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: windows-iis
  namespace: dotnet
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: windows-iis
  type: ClusterIP
